app = "rins-ai-core"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"
  WEBHOOK_URL = "https://rins-ai-core.fly.dev/"
  N8N_ALLOW_ENV_ACCESS = "true"
  N8N_DIAGNOSTICS_ENABLED = "false"
  N8N_VERSION_NOTIFICATIONS_ENABLED = "false"
  N8N_TEMPLATES_ENABLED = "false"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
